version: "3.8"
# volumes:
#   db-store:
#   redis-store:
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${WORK_DIR}:/var/www
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ${WORK_DIR}:/var/www
#     depends_on:
#       - db
#       - mailhog
#       - redis

#   db:
#     image: mysql:8.3
#     volumes:
#       # - ./mysql/data:/var/lib/mysql
#       - db-store:/var/lib/mysql
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       TZ: ${MYSQL_TZ}

  # phpmyadmin:
  #   image: phpmyadmin
  #   environment:
  #     PMA_HOST: "db"
  #     UPLOAD_LIMIT: 102400000
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db

#   mailhog:
#     image: mailhog/mailhog
#     ports:
#       - "1025:1025"
#       - "8025:8025" # メールボックス http://localhost:8020
#
#   redis:
#     image: redis:alpine
#     volumes:
#       - redis-store:/data
#     ports:
#       - "6379:6379"
